import { env } from "cloudflare:workers";
import { requireUser } from "../../../lib/auth";

type R = Record<string, any>;
const now = () => new Date().toISOString();
const admin = (u: R) => u.role === "admin";
const categories = ["Local travel","Fuel","Toll","Parking","Food / site refreshment","Courier / delivery","Material purchase","Small tools / consumables","Technician travel","Accommodation","Mobile / internet","Site visit","Emergency work","Office rent","Electricity / internet","Supplier payments","Stock / material purchases","Delivery / freight","Salaries","Marketing / advertising","Software subscriptions","Tools / equipment","Repairs","Professional fees","Bank charges","Other overheads","Other"];
const fields = ["expense_type","project_id","customer_id","site_id","lead_id","supplier_id","cost_centre","date","category","vendor","amount","tax","gstin","bill_number","paid_by","mode","description","distance_km","notes"];
const history = (uid:string,id:string,action:string,from:string|null,to:string|null,comment:string|null,snapshot:R={}) => env.DB.prepare("INSERT INTO expense_history(id,expense_id,action,from_status,to_status,comment,snapshot,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),id,action,from,to,comment,JSON.stringify(snapshot),uid,now()).run();
const notify = (uid:string,type:string,title:string,id:string) => env.DB.prepare("INSERT INTO notifications(id,user_id,type,title,entity_type,entity_id,created_at) VALUES(?,?,?,?,?,?,?)").bind(crypto.randomUUID(),uid,type,title,"expense",id,now()).run();
const receiptCount = async(id:string) => Number((await env.DB.prepare("SELECT COUNT(*) n FROM attachments WHERE entity_type='expense' AND entity_id=? AND archived=0").bind(id).first<{n:number}>())?.n||0);

export async function GET(req:Request){
 try{
  const user=await requireUser(),u=new URL(req.url),id=u.searchParams.get("id"),format=u.searchParams.get("format"),page=Math.max(1,Number(u.searchParams.get("page")||1)),limit=Math.min(100,Math.max(10,Number(u.searchParams.get("limit")||25))),where=["e.archived=0"],args:any[]=[];
  if(!admin(user)){where.push("e.created_by=?","e.expense_type='Claim'");args.push(user.id)}
  for(const [param,column] of [["status","e.status"],["category","e.category"],["project","e.project_id"],["employee","e.created_by"],["type","e.expense_type"]] as const){const value=u.searchParams.get(param);if(value&&(admin(user)||param!=="employee")){where.push(`${column}=?`);args.push(value)}}
  const from=u.searchParams.get("from"),to=u.searchParams.get("to"),q=(u.searchParams.get("q")||"").trim();if(from){where.push("e.date>=?");args.push(from)}if(to){where.push("e.date<=?");args.push(to)}if(q){where.push("(e.id LIKE ? OR e.description LIKE ? OR e.vendor LIKE ? OR e.bill_number LIKE ? OR p.title LIKE ?)");args.push(...Array(5).fill(`%${q}%`))}
  if(id){where.push("e.id=?");args.push(id)}
  const base=`FROM expenses e LEFT JOIN users creator ON creator.id=e.created_by LEFT JOIN users approver ON approver.id=e.approved_by LEFT JOIN projects p ON p.id=e.project_id LEFT JOIN customers c ON c.id=e.customer_id WHERE ${where.join(" AND ")}`;
  if(format==="csv"&&admin(user)){const rows=(await env.DB.prepare(`SELECT e.id,e.date,e.expense_type,creator.name employee,e.category,e.description,p.title project,e.vendor,e.amount,e.tax,e.approved_amount,e.paid_by,e.mode,e.status,e.reimbursement_date ${base} ORDER BY e.date DESC`).bind(...args).all<R>()).results,esc=(v:any)=>`"${String(v??"").replaceAll('"','""')}"`;const header="Expense ID,Date,Type,Employee,Category,Description,Project,Vendor,Amount,GST,Approved Amount,Paid By,Payment Mode,Status,Reimbursement Date\n",csv=rows.map(r=>Object.values(r).map(esc).join(",")).join("\n");return new Response(header+csv,{headers:{"content-type":"text/csv","content-disposition":"attachment; filename=Techomie-Expenses.csv"}})}
  const count=await env.DB.prepare(`SELECT COUNT(*) total ${base}`).bind(...args).first<{total:number}>(),rows=(await env.DB.prepare(`SELECT e.*,creator.name employee_name,approver.name approver_name,p.title project_title,c.name customer_name,(SELECT COUNT(*) FROM attachments a WHERE a.entity_type='expense' AND a.entity_id=e.id AND a.archived=0) receipt_count ${base} ORDER BY e.date DESC,e.created_at DESC LIMIT ? OFFSET ?`).bind(...args,limit,(page-1)*limit).all<R>()).results;
  if(id){const row=rows[0];if(!row)return Response.json({error:"Expense not found"},{status:404});const [receipts,events]=(await Promise.all([env.DB.prepare("SELECT id,file_name,file_key,content_type,size,created_at FROM attachments WHERE entity_type='expense' AND entity_id=? AND archived=0 ORDER BY created_at").bind(id).all(),env.DB.prepare("SELECT h.*,u.name user_name FROM expense_history h LEFT JOIN users u ON u.id=h.created_by WHERE h.expense_id=? ORDER BY h.created_at DESC").bind(id).all()]));return Response.json({expense:row,receipts:receipts.results,history:events.results})}
  const month=new Date().toISOString().slice(0,7),summary=await env.DB.prepare(`SELECT COALESCE(SUM(CASE WHEN substr(e.date,1,7)=? AND e.status!='Draft' THEN e.amount ELSE 0 END),0) submitted,COALESCE(SUM(CASE WHEN e.status IN ('Submitted','Under Review') THEN e.amount ELSE 0 END),0) pending,COALESCE(SUM(CASE WHEN e.status IN ('Approved','Reimbursement Pending') AND e.paid_by='Employee Personal Money' THEN COALESCE(e.approved_amount,e.amount) ELSE 0 END),0) unpaid,COALESCE(SUM(CASE WHEN substr(e.reimbursement_date,1,7)=? AND e.status='Reimbursed' THEN COALESCE(e.approved_amount,e.amount) ELSE 0 END),0) reimbursed ${base}`).bind(month,month,...args).first<R>();
  const masterRow=await env.DB.prepare("SELECT value FROM settings WHERE key='masters'").first<R>();let managedCategories=categories;try{const saved=JSON.parse(masterRow?.value||"{}").expenseCategories;if(Array.isArray(saved)&&saved.length)managedCategories=Array.from(new Set([...saved,...categories.slice(13)]))}catch{}
  const lookups:any={categories:managedCategories};if(admin(user)){lookups.users=(await env.DB.prepare("SELECT id,name FROM users WHERE active=1 ORDER BY name").all()).results;lookups.projects=(await env.DB.prepare("SELECT id,title FROM projects WHERE archived=0 ORDER BY title").all()).results}else{lookups.projects=(await env.DB.prepare("SELECT DISTINCT p.id,p.title FROM projects p LEFT JOIN project_team t ON t.project_id=p.id AND t.active=1 WHERE p.archived=0 AND (p.manager_id=? OR p.sales_id=? OR t.user_id=?) ORDER BY p.title").bind(user.id,user.id,user.id).all()).results}
  return Response.json({expenses:rows,summary,pagination:{page,limit,total:count?.total||0,pages:Math.ceil((count?.total||0)/limit)},lookups,admin:admin(user)});
 }catch(e){return e instanceof Response?e:Response.json({error:e instanceof Error?e.message:"Unable to load expenses"},{status:500})}
}

export async function POST(req:Request){
 try{const user=await requireUser(),p=await req.json() as R,type=String(p.expense_type||"Claim");if(type==="Company"&&!admin(user))return Response.json({error:"Only Admin can add company expenses"},{status:403});if(!p.date||!p.category||!(Number(p.amount)>0)||!p.mode)return Response.json({error:"Date, category, amount and payment method are required"},{status:400});const id=`EXP-${Date.now().toString().slice(-8)}`,t=now(),status=p.status==="Submitted"?"Submitted":"Draft",duplicate=await env.DB.prepare("SELECT id FROM expenses WHERE archived=0 AND date=? AND amount=? AND lower(vendor)=lower(?) AND created_by=? LIMIT 1").bind(p.date,Number(p.amount),p.vendor||"",user.id).first();const values:R={};for(const key of fields)if(p[key]!==undefined)values[key]=p[key];Object.assign(values,{expense_type:type,amount:Number(p.amount),tax:Number(p.tax||0),distance_km:p.distance_km?Number(p.distance_km):null,status,duplicate_warning:duplicate?1:0,created_by:user.id,submitted_at:status==="Submitted"?t:null,created_at:t,updated_at:t,archived:0});const keys=Object.keys(values);await env.DB.prepare(`INSERT INTO expenses(id,${keys.join(",")}) VALUES(?,${keys.map(()=>"?").join(",")})`).bind(id,...keys.map(k=>values[k])).run();await history(user.id,id,"Created",null,status,duplicate?"Possible duplicate detected":null,values);if(status==="Submitted"){const admins=(await env.DB.prepare("SELECT id FROM users WHERE role='admin' AND active=1").all<R>()).results;await Promise.all(admins.map(a=>notify(a.id,"expense_submitted",`New expense ${id} submitted`,id)))}return Response.json({expense:{id,status,duplicateWarning:!!duplicate}},{status:201})}catch(e){return e instanceof Response?e:Response.json({error:e instanceof Error?e.message:"Unable to create expense"},{status:500})}
}

export async function PATCH(req:Request){
 try{const user=await requireUser(),p=await req.json() as R,id=String(p.id||""),row=await env.DB.prepare("SELECT * FROM expenses WHERE id=? AND archived=0").bind(id).first<R>();if(!row)return Response.json({error:"Expense not found"},{status:404});const isOwner=row.created_by===user.id,action=String(p.action||"save"),t=now();if(!admin(user)&&!isOwner)return Response.json({error:"You can access only your own expenses"},{status:403});
  if(action==="save"){if(!["Draft","Returned for Correction"].includes(row.status))return Response.json({error:"This claim is locked while under review"},{status:423});const values:R={};for(const key of fields)if(p[key]!==undefined)values[key]=p[key];values.amount=Number(values.amount??row.amount);values.tax=Number(values.tax??row.tax);values.updated_at=t;const keys=Object.keys(values);await env.DB.prepare(`UPDATE expenses SET ${keys.map(k=>`${k}=?`).join(",")} WHERE id=?`).bind(...keys.map(k=>values[k]),id).run();await history(user.id,id,"Edited",row.status,row.status,"Draft autosaved",values);return Response.json({ok:true,savedAt:t})}
  if(action==="submit"){if(!isOwner||!["Draft","Returned for Correction"].includes(row.status))return Response.json({error:"Only an editable claim can be submitted"},{status:409});const settings=await env.DB.prepare("SELECT value FROM settings WHERE key='masters'").first<R>();let threshold=1000;try{threshold=Number(JSON.parse(settings?.value||"{}").expenseReceiptThreshold||1000)}catch{}if(Number(row.amount)>=threshold&&await receiptCount(id)===0)return Response.json({error:`Receipt required for expenses of ₹${threshold.toLocaleString("en-IN")} or more`},{status:400});await env.DB.prepare("UPDATE expenses SET status='Submitted',submitted_at=?,updated_at=? WHERE id=?").bind(t,t,id).run();await history(user.id,id,"Submitted",row.status,"Submitted",p.comment||null,row);const admins=(await env.DB.prepare("SELECT id FROM users WHERE role='admin' AND active=1").all<R>()).results;await Promise.all(admins.flatMap(a=>[notify(a.id,"expense_submitted",`Expense ${id} requires review`,id),...(Number(row.amount)>=10000?[notify(a.id,"expense_high_value",`High-value expense ${id}: ₹${Number(row.amount).toLocaleString("en-IN")}`,id)]:[]),...(row.duplicate_warning?[notify(a.id,"expense_duplicate",`Duplicate warning on ${id}`,id)]:[])]));return Response.json({ok:true,status:"Submitted"})}
  if(!admin(user))return Response.json({error:"Admin approval required"},{status:403});
  const transitions:R={review:"Under Review",return:"Returned for Correction",approve:row.paid_by==="Employee Personal Money"?"Reimbursement Pending":"Approved",reject:"Rejected",reimburse:"Reimbursed",cancel:"Cancelled"},next=transitions[action];if(!next)return Response.json({error:"Unsupported action"},{status:400});if(["return","reject"].includes(action)&&!p.comment)return Response.json({error:"A reason/comment is required"},{status:400});if(action==="approve"&&p.approvedAmount!==undefined&&Number(p.approvedAmount)>Number(row.amount))return Response.json({error:"Approved amount cannot exceed the claimed amount"},{status:400});if(action==="reimburse"&&(!p.paymentDate||!p.reference||!p.paymentMode))return Response.json({error:"Payment date, method and reference are required"},{status:400});const sets=["status=?","updated_at=?"],vals:any[]=[next,t];if(action==="approve"){sets.push("approved_amount=?","approved_by=?","approved_at=?","approver_comment=?");vals.push(Number(p.approvedAmount??row.amount),user.id,t,p.comment||null)}if(action==="reject"){sets.push("approved_by=?","rejection_reason=?");vals.push(user.id,p.comment)}if(action==="return"){sets.push("approver_comment=?");vals.push(p.comment)}if(action==="reimburse"){sets.push("reimbursement_date=?","reimbursement_mode=?","reimbursement_reference=?","payer=?");vals.push(p.paymentDate,p.paymentMode,p.reference,p.payer||user.name)}await env.DB.prepare(`UPDATE expenses SET ${sets.join(",")} WHERE id=?`).bind(...vals,id).run();await history(user.id,id,action,row.status,next,p.comment||p.reference||null,p);if(row.created_by)await notify(row.created_by,`expense_${action}`,`Expense ${id} ${next.toLowerCase()}`,id);return Response.json({ok:true,status:next})
 }catch(e){return e instanceof Response?e:Response.json({error:e instanceof Error?e.message:"Unable to update expense"},{status:500})}
}
