// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/setup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/setup">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/setup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/status">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/customers/attachments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customers/attachments">> = Specific
  const handler = {} as typeof import("../../../app/api/customers/attachments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/customers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customers">> = Specific
  const handler = {} as typeof import("../../../app/api/customers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/expenses/receipts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expenses/receipts">> = Specific
  const handler = {} as typeof import("../../../app/api/expenses/receipts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/expenses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expenses">> = Specific
  const handler = {} as typeof import("../../../app/api/expenses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/invoices/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invoices/cancel">> = Specific
  const handler = {} as typeof import("../../../app/api/invoices/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/invoices/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invoices/pdf">> = Specific
  const handler = {} as typeof import("../../../app/api/invoices/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/invoices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invoices">> = Specific
  const handler = {} as typeof import("../../../app/api/invoices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/leads/activity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/activity">> = Specific
  const handler = {} as typeof import("../../../app/api/leads/activity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/leads/attachments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/attachments">> = Specific
  const handler = {} as typeof import("../../../app/api/leads/attachments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/leads/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/export">> = Specific
  const handler = {} as typeof import("../../../app/api/leads/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/leads/followups/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/followups">> = Specific
  const handler = {} as typeof import("../../../app/api/leads/followups/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/leads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads">> = Specific
  const handler = {} as typeof import("../../../app/api/leads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/leads/visits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/visits">> = Specific
  const handler = {} as typeof import("../../../app/api/leads/visits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/overview">> = Specific
  const handler = {} as typeof import("../../../app/api/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products">> = Specific
  const handler = {} as typeof import("../../../app/api/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/sync">> = Specific
  const handler = {} as typeof import("../../../app/api/products/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/projects/attachments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/attachments">> = Specific
  const handler = {} as typeof import("../../../app/api/projects/attachments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects">> = Specific
  const handler = {} as typeof import("../../../app/api/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/quotations/files/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quotations/files">> = Specific
  const handler = {} as typeof import("../../../app/api/quotations/files/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/quotations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quotations">> = Specific
  const handler = {} as typeof import("../../../app/api/quotations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/quotations/workspace/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quotations/workspace">> = Specific
  const handler = {} as typeof import("../../../app/api/quotations/workspace/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/records/[entity]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/records/[entity]">> = Specific
  const handler = {} as typeof import("../../../app/api/records/[entity]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/site-visits/attachments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/site-visits/attachments">> = Specific
  const handler = {} as typeof import("../../../app/api/site-visits/attachments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/site-visits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/site-visits">> = Specific
  const handler = {} as typeof import("../../../app/api/site-visits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/uploads/[name]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/uploads/[name]">> = Specific
  const handler = {} as typeof import("../../../app/api/uploads/[name]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/uploads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/uploads">> = Specific
  const handler = {} as typeof import("../../../app/api/uploads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users">> = Specific
  const handler = {} as typeof import("../../../app/api/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
