"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, @next/next/no-img-element */
import { useCallback, useEffect, useMemo, useState } from "react";

type R = Record<string, any>;
const money = (value: any) => value == null ? "Not priced" : new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(Number(value));
const tabs = ["Customer-facing details", "Technical configuration", "Variants and compatibility", "Images and media", "Selling prices", "Supplier and purchase prices", "Warranty", "Compatible accessories", "Import source", "Audit history"];

export default function ItemMasterModule({ isAdmin }: { isAdmin: boolean }) {
  const [items, setItems] = useState<R[]>([]), [meta, setMeta] = useState({ page: 1, pages: 1, total: 0 }), [q, setQ] = useState(""), [status, setStatus] = useState(""), [detail, setDetail] = useState<R | null>(null), [review, setReview] = useState<R | null>(null), [msg, setMsg] = useState(""), [busy, setBusy] = useState(false);
  const load = useCallback(async (page = 1) => {
    const params = new URLSearchParams({ q, status, page: String(page) }), response = await fetch(`/api/item-master?${params}`), data = await response.json();
    if (response.ok) { setItems(data.items || []); setMeta(data.pagination); } else setMsg(data.error);
  }, [q, status]);
  useEffect(() => { const timer = setTimeout(() => load(1), q ? 180 : 0); return () => clearTimeout(timer); }, [load, q]);
  const open = async (id: string) => { const response = await fetch(`/api/item-master?id=${encodeURIComponent(id)}`), data = await response.json(); if (response.ok) setDetail(data); else setMsg(data.error); };
  const loadReview = async () => { const response = await fetch("/api/item-master?view=imports"), data = await response.json(); if (response.ok) setReview(data); else setMsg(data.error); };
  const stage = async (file: File) => {
    setBusy(true); setMsg("Staging normalized supplier data for review…");
    try { const pkg = JSON.parse(await file.text()), response = await fetch("/api/item-master", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "stage", package: pkg }) }), data = await response.json(); if (!response.ok) throw new Error(data.error); setMsg(`Import staged: ${data.summary.baseItems} base items, ${data.summary.variants} variants. Nothing is published until approval.`); await loadReview(); await load(); } catch (error) { setMsg(error instanceof Error ? error.message : "Import failed"); } finally { setBusy(false); }
  };
  const priceRange = (item: R) => item.min_selling_price == null ? "Needs pricing" : item.min_selling_price === item.max_selling_price ? money(item.min_selling_price) : `${money(item.min_selling_price)} – ${money(item.max_selling_price)}`;
  return <div className="itemsmaster authoritativeitems">
    <div className="itemshero"><div><small>AUTHORITATIVE COMMERCIAL + TECHNICAL DATABASE</small><h1>Item Master</h1><p>Supplier identities, internal configurations and approved customer-facing items remain separate.</p></div>{isAdmin && <div className="itemmasteractions"><button onClick={loadReview}>Import review</button><label className={busy ? "disabled" : "primary"}>Stage normalized import<input type="file" accept="application/json,.json" disabled={busy} onChange={event => event.target.files?.[0] && stage(event.target.files[0])}/></label></div>}</div>
    {msg && <div className="itemsmsg">{msg}<button onClick={() => setMsg("")}>×</button></div>}
    <div className="itemsfilters"><label className="itemssearch">⌕<input value={q} onChange={event => setQ(event.target.value)} placeholder="Customer item, internal code, series or configuration"/></label>{isAdmin && <select value={status} onChange={event => setStatus(event.target.value)}><option value="">All review states</option>{["Imported", "Needs Review", "Approved", "Active"].map(value => <option key={value}>{value}</option>)}</select>}</div>
    <div className="mastertable"><div className={`masterrow masterhead ${isAdmin ? "admin" : ""}`}><span>Image</span><span>Customer-facing item</span><span>Internal code</span><span>Brand / Category</span><span>Base configuration</span><span>Variants</span><span>Selling price</span><span>Availability / Image</span>{isAdmin && <><span>Supplier / model</span><span>Current buying</span></>}<span>State</span></div>
      {items.map(item => <button className={`masterrow ${isAdmin ? "admin" : ""}`} key={item.id} onClick={() => open(item.id)}><span className="itemimage">{item.image_key ? <img src={item.image_key.startsWith("/") ? item.image_key : `/api/uploads/${item.image_key}`} alt=""/> : <i>No image</i>}</span><span><b>{item.customer_name}</b><small>{item.procurement_name}</small></span><span><b>{item.internal_code}</b><small>{item.series || "Fixed model"}</small></span><span><b>{item.brand || "Mapping required"}</b><small>{item.category || "Uncategorised"}</small></span><span>{item.procurement_name}</span><span><b>{item.variant_count}</b></span><span><b>{priceRange(item)}</b></span><span><b>{item.availability}</b><small>{item.image_status}</small></span>{isAdmin && <><span><b>{item.supplier_name || "—"}</b><small>{item.supplier_model || "—"}</small></span><span><b>{money(item.net_buying_price)}</b></span></>}<span><em>{item.review_status}</em><small>{item.active ? "Active" : "Not published"}</small></span></button>)}</div>
    <div className="itempages"><span>{meta.total} base items</span><button disabled={meta.page <= 1} onClick={() => load(meta.page - 1)}>Previous</button><span>Page {meta.page} / {meta.pages || 1}</span><button disabled={meta.page >= meta.pages} onClick={() => load(meta.page + 1)}>Next</button></div>
    {detail && <MasterDetail data={detail} admin={isAdmin} close={() => setDetail(null)} refresh={() => open(detail.item.id)} notify={setMsg}/>} {review && <ImportReview data={review} close={() => setReview(null)}/>} 
  </div>;
}

function MasterDetail({ data, admin, close, refresh, notify }: { data: R; admin: boolean; close: () => void; refresh: () => void; notify: (value: string) => void }) {
  const [tab, setTab] = useState(tabs[0]), item = data.item;
  const patch = async (body: R) => { const response = await fetch("/api/item-master", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }), result = await response.json(); if (!response.ok) return notify(result.error); notify("Item Master updated"); refresh(); };
  return <div className="itemdrawer masterdetail"><header><div><small>{item.internal_code} · {item.review_status}</small><h2>{item.customer_name}</h2><p>{item.procurement_name}</p></div><button onClick={close}>×</button></header><nav>{tabs.map(value => <button key={value} className={tab === value ? "active" : ""} onClick={() => setTab(value)}>{value}</button>)}</nav><main>
    {tab === "Customer-facing details" && <div className="masteridentity"><section><small>CUSTOMER IDENTITY</small><h3>{item.customer_brand || "Brand mapping required"}</h3><p>{item.description || "Customer description requires review."}</p>{admin && <button onClick={() => { const brand = prompt("Customer-facing brand (NOVIQ, supplier brand, third-party brand, or Unbranded/OEM)", item.customer_brand || "Unbranded/OEM"), customerName = brand && prompt("Approved customer-facing product name", item.customer_name); if (brand && customerName) patch({ action: "set-brand-mapping", id: item.id, brand, customerName }); }}>Approve brand and name</button>}</section><section><small>INTERNAL IDENTITY</small><h3>{item.procurement_name}</h3><p>{item.internal_code} · {item.category_name} · {item.series}</p></section></div>}
    {tab === "Technical configuration" && <RecordCards rows={data.configurations} empty="No structured configuration"/>}
    {tab === "Variants and compatibility" && <RecordCards rows={data.variants} empty="No sellable variants"/>}
    {tab === "Images and media" && <div className="mediagrid">{data.media?.map((media: R) => <article key={media.id}>{media.file_key ? <img src={media.file_key.startsWith("/") ? media.file_key : `/api/uploads/${media.file_key}`} alt=""/> : <div>Missing image</div>}<b>{media.kind}</b><small>{media.review_status}{media.review_issue ? ` · ${media.review_issue}` : ""}</small>{admin && !media.customer_approved && <button onClick={() => patch({ action: "approve-media", mediaId: media.id })}>Approve for quotation</button>}</article>)}</div>}
    {tab === "Selling prices" && <div className="variantrecords">{data.variants?.map((variant: R) => <article key={variant.id}><span><b>{[variant.technology, variant.material, variant.finish].filter(Boolean).join(" · ") || "Fixed model"}</b><small>{variant.internal_item_id} · {variant.selling_method}</small></span><strong>{money(variant.selling_price)}</strong>{admin && <button onClick={() => { const value = prompt("Approved selling price", String(variant.selling_price || "")); if (value && Number(value) > 0) patch({ action: "set-selling-price", variantId: variant.id, price: Number(value) }); }}>Set price</button>}</article>)}</div>}
    {tab === "Supplier and purchase prices" && (admin ? <RecordCards rows={data.supplierItems} empty="No supplier mapping"/> : <p>Supplier and purchase information is restricted to administrators.</p>)}
    {tab === "Warranty" && <RecordCards rows={[{ warranty: item.warranty || "Warranty template requires approval", hsnSac: item.hsn_sac, gst: item.gst_rate }]} empty="No warranty"/>}
    {tab === "Compatible accessories" && <p>Compatible accessories and required procurement components are managed independently from customer visibility.</p>}
    {tab === "Import source" && (admin ? <RecordCards rows={data.supplierItems?.map((row: R) => ({ supplier: row.supplier_name, model: row.supplier_model, priceBook: row.price_book_name, effectiveDate: row.effective_date, sourceSheet: row.source_sheet, sourcePage: row.source_page, sourceRow: row.source_row }))} empty="No import source"/> : <p>Import source is restricted to administrators.</p>)}
    {tab === "Audit history" && (admin ? <RecordCards rows={data.audit} empty="No Item Master changes recorded"/> : <p>Audit history is restricted to administrators.</p>)}
  </main>{admin && <footer><span>Approval publishes only fully mapped customer data.</span><button className="primary" onClick={() => patch({ action: "approve-item", id: item.id })}>Approve and activate</button></footer>}</div>;
}

function RecordCards({ rows = [], empty }: { rows?: R[]; empty: string }) { return <div className="recordcards">{rows.length ? rows.map((row, index) => <article key={row.id || index}>{Object.entries(row).filter(([key, value]) => value !== null && value !== "" && !["id", "base_product_id", "variant_id"].includes(key)).map(([key, value]) => <span key={key}><small>{key.replaceAll("_", " ")}</small><b>{typeof value === "object" ? JSON.stringify(value) : String(value)}</b></span>)}</article>) : <p>{empty}</p>}</div>; }

function ImportReview({ data, close }: { data: R; close: () => void }) {
  const counts = useMemo(() => data.errors?.reduce((result: R, row: R) => ({ ...result, [row.code]: (result[row.code] || 0) + 1 }), {}) || {}, [data]);
  return <div className="itemdrawer importreview"><header><div><small>REVIEW-FIRST SUPPLIER IMPORTS</small><h2>Import validation</h2><p>Imported → Needs Review → Approved → Active</p></div><button onClick={close}>×</button></header><main><div className="reviewstats">{Object.entries(counts).map(([key, value]) => <span key={key}><b>{String(value)}</b><small>{key.replaceAll("_", " ")}</small></span>)}</div><h3>Import jobs</h3><RecordCards rows={data.jobs} empty="No imports staged"/><h3>Unresolved review items</h3><RecordCards rows={data.errors} empty="No unresolved import issues"/></main></div>;
}
