"use client";
import { useEffect,useState } from "react";

type Nav=(module:string,filter?:Record<string,string>)=>void;
const money=(v:unknown)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(v||0));
const labels:Record<string,string>={new:'New leads',notContacted:'Not contacted',followupsToday:"Today's follow-ups",followupsOverdue:'Overdue follow-ups',siteVisits:'Upcoming site visits',draft:'Draft',sent:'Sent',value:'Value',followup:'Awaiting follow-up',expiring:'Expiring soon',accepted:'Accepted',rejected:'Rejected',finalised:'Finalised',received:'Amount received',pending:'Pending balance',overdue:'Overdue',active:'Active projects',installationsToday:'Installations today',delayed:'Delayed',handovers:'Handovers due',waiting:'Waiting for readiness',due:'Due at site',purchasePending:'Purchase value pending',today:"Today's collection",month:'This month',open:'Open tickets',assignedToday:'Assigned today',renewals:'Renewals due'};
const financial=new Set(['value','received','pending','purchasePending','today','month']);

export default function OverviewModule({role,onNavigate}:{role:string;onNavigate:Nav}){const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[filters,setFilters]=useState({period:'today',from:'',to:'',employee:'',city:'',source:'',category:'',q:''});
 const load=async()=>{setLoading(true);setError('');const p=new URLSearchParams(Object.entries(filters).filter(([,v])=>v));const r=await fetch(`/api/overview?${p}`),d=await r.json();setLoading(false);if(r.ok)setData(d);else setError(d.error||'Unable to load overview')};useEffect(()=>{const t=setTimeout(load,filters.q?250:0);return()=>clearTimeout(t)},[filters]);
 const go=(m:string,f?:Record<string,string>)=>onNavigate(m,f), quick=[['Add Lead','Leads'],['Create Quote','Quotations'],['Create Invoice','Invoices'],['Add Expense','Expenses'],['Add Project','Projects'],['Record Payment','Payments']].filter(x=>role==='admin'||!['Expenses'].includes(x[1]));
 if(loading&&!data)return <div className="controlroom loadingroom"><div className="controlpulse"/><h2>Loading today’s control room…</h2></div>;if(error)return <div className="modulepage"><p className="formerror">{error}</p><button className="primary" onClick={load}>Try again</button></div>;
 const sections=[['Leads','Leads',data.kpis.leads],['Quotations','Quotations',data.kpis.quotes],['Invoices','Invoices',data.kpis.invoices],['Projects','Projects',data.kpis.projects],['Procurement','Procurement',data.kpis.procurement],['Payments','Payments',data.kpis.payments],...(data.kpis.expenses?[['Expenses','Expenses',data.kpis.expenses]]:[]),['Service','Service',data.kpis.service]] as any[];
 return <div className="controlroom"><div className="controltop"><div><small>DAILY OPERATIONS CONTROL ROOM</small><h1>Good day, {data.user.name.split(' ')[0]}</h1><p>{data.filters.from} to {data.filters.to} · Live database view · {role==='admin'?'All-company access':'Your assigned work only'}</p></div><div className="quickactions">{quick.map(([label,m])=><button key={label} onClick={()=>go(m)}>＋ {label}</button>)}</div></div>
 <div className="controlfilters"><div className="periodtabs">{[['today','Today'],['week','This Week'],['month','This Month'],['fy','Financial Year'],['custom','Custom']].map(x=><button className={filters.period===x[0]?'active':''} key={x[0]} onClick={()=>setFilters({...filters,period:x[0]})}>{x[1]}</button>)}</div>{filters.period==='custom'&&<><input type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/><input type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></>}<select value={filters.employee} onChange={e=>setFilters({...filters,employee:e.target.value})} disabled={role!=='admin'}><option value="">{role==='admin'?'All employees':'My records'}</option>{data.filters.employees.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input placeholder="City" value={filters.city} onChange={e=>setFilters({...filters,city:e.target.value})}/><input placeholder="Lead source" value={filters.source} onChange={e=>setFilters({...filters,source:e.target.value})}/><input placeholder="Project category" value={filters.category} onChange={e=>setFilters({...filters,category:e.target.value})}/><label className="globalsearch">⌕<input placeholder="Customer, quote, invoice, project or phone" value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value})}/></label></div>
 <div className="kpicategories">{sections.map(([title,module,items])=><section className="kpicategory" key={title}><div className="categorytitle"><span>{title.slice(0,2).toUpperCase()}</span><h2>{title}</h2></div><div>{Object.entries(items).map(([key,value])=><button key={key} onClick={()=>go(module,{metric:key})}><small>{labels[key]||key}</small><b>{typeof value==='number'&&(financial.has(key)||['value','received','pending','overdue','today','month','purchasePending'].includes(key))&&value>999?money(value):String(value)}</b><i>Open →</i></button>)}</div></section>)}</div>
 <section className="prioritysection"><SectionTitle eyebrow="ACT NOW" title="Today’s Priority Actions" count={data.priority.length}/><div className="prioritylist">{data.priority.length?data.priority.map((x:any,i:number)=><button key={`${x.kind}-${x.id}-${i}`} className={x.severity==='high'?'urgent':''} onClick={()=>go(x.module,{id:String(x.id)})}><span className="priorityicon">{x.kind.slice(0,1).toUpperCase()}</span><span><b>{x.title}</b><small>{x.meta}</small></span><strong>{x.action} →</strong></button>):<Empty text="No priority actions for this period"/>}</div></section>
 <div className="controlgrid"><section className="controlpanel pipelinepanel"><SectionTitle eyebrow="LEADS" title="Pipeline & Follow-ups"/><div className="pipeline">{data.pipeline.map((x:any)=><button key={x.stage} onClick={()=>go('Leads',{status:x.stage})}><span>{x.stage}</span><b>{x.count}</b><small>{x.value?money(x.value):'No value entered'}</small><i style={{width:`${Math.min(100,x.count*12)}%`}}/></button>)}</div></section><section className="controlpanel"><SectionTitle eyebrow="QUOTATIONS" title="Performance"/><div className="bigmetrics"><Metric label="Created this month" value={data.quotationPerformance.created} onClick={()=>go('Quotations')}/><Metric label="Quote amount" value={money(data.quotationPerformance.amount)} onClick={()=>go('Quotations')}/><Metric label="Accepted amount" value={money(data.quotationPerformance.accepted)} onClick={()=>go('Quotations')}/><Metric label="Conversion" value={`${data.quotationPerformance.conversion.toFixed(1)}%`} onClick={()=>go('Quotations')}/></div><h3>Highest-value pending quotations</h3><CompactList rows={data.quotationPerformance.pending} empty="No pending quotations" onClick={()=>go('Quotations')} title={(x:any)=>`${x.number} · ${x.customer_name||'Customer'}`} meta={(x:any)=>money(x.total)}/></section></div>
 <div className="controlgrid"><section className="controlpanel"><SectionTitle eyebrow="RECEIVABLES" title="Invoice & Collection Summary"/><div className="bigmetrics"><Metric label="Total invoiced" value={money(data.collections.invoiced)} onClick={()=>go('Invoices')}/><Metric label="Collected" value={money(data.collections.collected)} onClick={()=>go('Payments')}/><Metric label="Pending" value={money(data.collections.pending)} onClick={()=>go('Invoices')}/><Metric label="Overdue" value={money(data.collections.overdue)} onClick={()=>go('Invoices')}/></div><h3>Invoice-wise pending</h3><CompactList rows={data.collections.invoices} empty="No overdue invoices" onClick={(x:any)=>go('Invoices',{id:x.id})} title={(x:any)=>`${x.number} · ${x.customer_name}`} meta={(x:any)=>money(x.grand_total)}/></section><section className="controlpanel"><SectionTitle eyebrow="PAYMENT MILESTONES" title="Pending by stage"/><div className="milestones">{data.collections.milestones.map((x:any)=><button key={x.name} onClick={()=>go('Payments',{milestone:x.name})}><span>{x.name}</span><b>{money(x.value)}</b></button>)}</div></section></div>
 <section className="projectboard"><SectionTitle eyebrow="DELIVERY" title="Project Status Board" count={data.projects.length}/><div className="stagebar">{data.projectStages.map((x:any)=><button key={x.stage} onClick={()=>go('Projects',{status:x.stage})}><b>{x.count}</b><span>{x.stage}</span></button>)}</div><div className="projectcards">{data.projects.length?data.projects.map((p:any)=><button key={p.id} onClick={()=>go('Projects',{id:p.id})}><div><em>{p.status}</em><b>{p.title}</b><span>{p.customer} · {p.site||'Site not set'}</span></div><dl><div><dt>Assigned</dt><dd>{p.staff}</dd></div><div><dt>Next task</dt><dd>{p.nextTask}</dd></div><div><dt>Due</dt><dd>{p.dueDate}</dd></div><div><dt>Payment</dt><dd>{p.paymentStatus}</dd></div><div><dt>Material</dt><dd>{p.materialStatus}</dd></div></dl><strong>Open project →</strong></button>):<Empty text="No active projects match these filters"/>}</div></section>
 <div className="controlgrid"><section className="controlpanel"><SectionTitle eyebrow="PROCUREMENT" title="Material Alerts"/><CompactList rows={data.procurement} empty="No materials due" onClick={(x:any)=>go('Procurement',{id:x.id})} title={(x:any)=>x.name} meta={(x:any)=>`${x.project_title} · ${x.received_qty}/${x.required_qty} received · due ${x.expected_delivery||'not set'}`}/></section>{data.cash&&<section className="controlpanel cashpanel"><SectionTitle eyebrow="ADMIN ONLY" title="Cash & Expense Summary"/><div className="cashgrid">{[['Sales this month',data.cash.sales],['Collections',data.cash.collections],['Expenses',data.cash.expenses],['Supplier payments pending',data.cash.supplierPending],['Customer collections pending',data.cash.customerPending],['Estimated gross margin',data.cash.grossMargin],['Net cash flow',data.cash.netCash]].map(x=><button key={String(x[0])} onClick={()=>go(String(x[0]).includes('Expense')?'Expenses':String(x[0]).includes('Supplier')?'Procurement':'Payments')}><small>{x[0]}</small><b>{money(x[1])}</b></button>)}</div><h3>Expense split</h3><div className="expensesplit">{data.cash.expenseSplit.map((x:any)=><button key={x.category} onClick={()=>go('Expenses',{category:x.category})}><span>{x.category}</span><b>{money(x.value)}</b></button>)}</div></section>}</div>
 <section className="controlpanel teampanel"><SectionTitle eyebrow="ACCOUNTABILITY" title="Team Performance"/><div className="teamtable"><div className="teamrow teamhead"><span>Employee</span><span>Leads</span><span>Follow-ups today</span><span>Overdue tasks</span><span>Quotes</span><span>Completed</span><span>Jobs pending</span></div>{data.team.map((x:any)=><button className="teamrow" key={x.id} onClick={()=>role==='admin'&&setFilters({...filters,employee:x.id})}><span><b>{x.name}</b><small>{x.role}</small></span><span>{x.leads}</span><span>{x.followups}</span><span>{x.overdueTasks}</span><span>{x.quotes}</span><span>{x.completed}</span><span>{x.jobsPending}</span></button>)}</div></section>
 <div className="controlgrid"><section className="controlpanel"><SectionTitle eyebrow="SERVICE" title="Warranty, AMC & Service Alerts"/><h3>Urgent and overdue tickets</h3><CompactList rows={[...data.serviceAlerts.urgent,...data.serviceAlerts.overdue].slice(0,10)} empty="No urgent service alerts" onClick={(x:any)=>go('Service',{id:x.id})} title={(x:any)=>`${x.customer_name} · ${x.priority}`} meta={(x:any)=>x.problem}/><h3>Renewals due within 30 days</h3><CompactList rows={data.serviceAlerts.renewals} empty="No renewals due" onClick={()=>go('Service')} title={(x:any)=>`${x.renewal_type} · ${x.customer_name}`} meta={(x:any)=>`Due ${x.end_date}`}/></section><section className="controlpanel timelinepanel"><SectionTitle eyebrow="AUDIT TRAIL" title="Recent Activity Timeline"/><div>{data.activity.length?data.activity.map((x:any)=><button key={x.id} onClick={()=>go(x.module,{id:String(x.entityId)})}><i/><span><b>{x.user}</b> {x.text}</span><time>{new Date(x.time).toLocaleString('en-IN')}</time></button>):<Empty text="No recent activity"/>}</div></section></div>
 </div>}

function SectionTitle({eyebrow,title,count}:{eyebrow:string;title:string;count?:number}){return <div className="sectiontitle"><div><small>{eyebrow}</small><h2>{title}</h2></div>{count!==undefined&&<span>{count} items</span>}</div>}
function Metric({label,value,onClick}:{label:string;value:string|number;onClick:()=>void}){return <button onClick={onClick}><small>{label}</small><b>{value}</b><span>View details →</span></button>}
function CompactList({rows,empty,onClick,title,meta}:{rows:any[];empty:string;onClick:(x:any)=>void;title:(x:any)=>string;meta:(x:any)=>string}){return <div className="compactlist">{rows.length?rows.map((x:any,i:number)=><button key={String(x.id||i)} onClick={()=>onClick(x)}><span><b>{title(x)}</b><small>{meta(x)}</small></span><strong>Open →</strong></button>):<Empty text={empty}/>}</div>}
function Empty({text}:{text:string}){return <div className="controlempty">✓ {text}</div>}
