import { env } from "cloudflare:workers";
import { requireUser } from "../../../lib/auth";

type Row=Record<string,unknown>;
const n=(v:unknown)=>Number(v||0),s=(v:unknown)=>String(v||"").toLowerCase();
const day=(d:Date)=>d.toISOString().slice(0,10);
const range=(period:string,from:string|null,to:string|null)=>{const now=new Date(),end=to||day(now),start=new Date(now);if(period==="today")return{from:day(now),to:end};if(period==="week")start.setDate(now.getDate()-((now.getDay()+6)%7));else if(period==="month")start.setDate(1);else if(period==="fy")start.setFullYear(now.getMonth()<3?now.getFullYear()-1:now.getFullYear(),3,1);return{from:from||day(start),to:end}};
const within=(v:unknown,a:string,b:string)=>{const x=String(v||"").slice(0,10);return !!x&&x>=a&&x<=b};
const sum=(rows:Row[],key:string)=>rows.reduce((a,r)=>a+n(r[key]),0);
const first=(...values:unknown[])=>values.find(Boolean)||"";

export async function GET(req:Request){try{const user=await requireUser(),u=new URL(req.url),period=u.searchParams.get("period")||"today",dates=range(period,u.searchParams.get("from"),u.searchParams.get("to")),employee=u.searchParams.get("employee")||"",city=s(u.searchParams.get("city")),source=s(u.searchParams.get("source")),category=s(u.searchParams.get("category")),query=s(u.searchParams.get("q")),admin=user.role==="admin",scope=admin?(employee||""):user.id,today=day(new Date()),three=day(new Date(Date.now()+3*86400000)),monthStart=today.slice(0,7)+"-01";
 const all=async(sql:string)=>(await env.DB.prepare(sql).all<Row>()).results;
 const [users,leads,quotes,invoices,projects,materials,payments,invoicePayments,expenses,tasks,service,amc,warranties,activities,audit]=await Promise.all([
  all("SELECT id,name,role FROM users WHERE active=1 ORDER BY name"),
  all("SELECT * FROM leads WHERE archived=0 ORDER BY created_at DESC LIMIT 1000"),
  all("SELECT q.*,c.name customer_name,c.phone,c.lead_source,s.name site_name,s.address site_address FROM quotations q LEFT JOIN customers c ON c.id=q.customer_id LEFT JOIN customer_sites s ON s.id=q.site_id ORDER BY q.created_at DESC LIMIT 1000"),
  all("SELECT i.*,c.name customer_name,c.phone FROM tax_invoices i JOIN customers c ON c.id=i.customer_id ORDER BY i.created_at DESC LIMIT 1000"),
  all("SELECT p.*,c.name customer_name,c.phone,cs.name site_name,cs.city,cs.address site_address,u.name manager_name FROM projects p JOIN customers c ON c.id=p.customer_id LEFT JOIN customer_sites cs ON cs.id=p.site_id LEFT JOIN users u ON u.id=p.manager_id WHERE p.archived=0 ORDER BY p.updated_at DESC LIMIT 1000"),
  all("SELECT m.*,p.manager_id,p.title project_title,c.name customer_name,cs.name site_name FROM project_materials m JOIN projects p ON p.id=m.project_id JOIN customers c ON c.id=p.customer_id LEFT JOIN customer_sites cs ON cs.id=p.site_id ORDER BY m.updated_at DESC LIMIT 1000"),
  all("SELECT p.*,pr.manager_id,pr.title project_title FROM payments p LEFT JOIN projects pr ON pr.id=p.project_id WHERE p.archived=0 ORDER BY p.date DESC LIMIT 1000"),
  all("SELECT p.*,i.created_by invoice_owner FROM invoice_payments p JOIN tax_invoices i ON i.id=p.invoice_id ORDER BY p.date DESC LIMIT 1000"),
  admin?all("SELECT * FROM expenses WHERE archived=0 ORDER BY date DESC LIMIT 1000"):Promise.resolve([]),
  all("SELECT t.*,p.manager_id,p.title project_title,c.name customer_name FROM project_tasks t JOIN projects p ON p.id=t.project_id JOIN customers c ON c.id=p.customer_id ORDER BY t.created_at DESC LIMIT 1000"),
  all("SELECT st.*,c.name customer_name,cs.name site_name FROM service_tickets st JOIN customers c ON c.id=st.customer_id LEFT JOIN customer_sites cs ON cs.id=st.site_id WHERE st.archived=0 ORDER BY st.updated_at DESC LIMIT 1000"),
  all("SELECT a.*,c.name customer_name FROM amc_contracts a JOIN customers c ON c.id=a.customer_id ORDER BY a.end_date LIMIT 500"),
  all("SELECT w.*,c.name customer_name FROM warranties w JOIN customers c ON c.id=w.customer_id ORDER BY w.service_end LIMIT 500"),
  all("SELECT * FROM activities ORDER BY created_at DESC LIMIT 1000"),
  all("SELECT a.*,u.name user_name FROM audit_log a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 80")
 ]);
 const matches=(r:Row)=>{if(query&&!Object.values(r).some(v=>s(v).includes(query)))return false;if(city&&!s(first(r.city,r.site_address,r.address)).includes(city))return false;if(source&&!s(first(r.source,r.lead_source)).includes(source))return false;if(category&&!s(first(r.requirement,r.title,r.project_title,r.category)).includes(category))return false;return true};
 const assigned=(r:Row)=>!scope||[r.assigned_to,r.created_by,r.manager_id,r.received_by,r.invoice_owner].some(v=>String(v||"")===scope);
 const L=leads.filter(r=>assigned(r)&&matches(r)),Q=quotes.filter(r=>assigned(r)&&matches(r)),I=invoices.filter(r=>assigned(r)&&matches(r)),P=projects.filter(r=>assigned(r)&&matches(r)),M=materials.filter(r=>assigned(r)&&matches(r)),Pay=payments.filter(r=>assigned(r)&&matches(r)),IPay=invoicePayments.filter(r=>assigned(r)&&matches(r)),T=tasks.filter(r=>assigned(r)&&matches(r)),S=service.filter(r=>assigned(r)&&matches(r)),A=activities.filter(r=>assigned(r)&&matches(r));
 const periodRows=(rows:Row[],key:string)=>rows.filter(r=>within(r[key],dates.from,dates.to)),newLeads=periodRows(L,"created_at"),followToday=L.filter(r=>within(r.followup_at,today,today)&&!['won','lost'].includes(s(r.status))),followOver=L.filter(r=>String(r.followup_at||"").slice(0,10)<today&&!['won','lost'].includes(s(r.status))),siteVisits=A.filter(r=>s(r.type).includes('site')&&within(r.due_at,today,today)&&!r.completed_at),draftQ=Q.filter(r=>s(r.status)==='draft'),sentQ=Q.filter(r=>s(r.status).includes('sent')),acceptedQ=Q.filter(r=>['accepted','won','invoiced'].includes(s(r.status))),rejectedQ=Q.filter(r=>['rejected','lost'].includes(s(r.status))),pendingQ=Q.filter(r=>!['accepted','won','invoiced','rejected','lost'].includes(s(r.status))),expiringQ=pendingQ.filter(r=>{const expiry=new Date(String(r.created_at));expiry.setDate(expiry.getDate()+30);return day(expiry)>=today&&day(expiry)<=three}),finalI=I.filter(r=>s(r.status)!=='draft'&&s(r.status)!=='cancelled'),draftI=I.filter(r=>s(r.status)==='draft'),paidTotal=sum(IPay,"amount"),invoiceTotal=sum(finalI,"grand_total"),pending=Math.max(0,invoiceTotal-paidTotal),overdueI=finalI.filter(r=>s(r.status)!=='paid'&&String(r.due_date||'9999').slice(0,10)<today),activeP=P.filter(r=>!['completed','cancelled'].includes(s(r.status))),delayedP=activeP.filter(r=>String(r.planned_end||'9999').slice(0,10)<today),installs=P.filter(r=>s(r.status).includes('installation')&&within(first(r.planned_start,r.updated_at),today,today)),handover=P.filter(r=>s(r.status).includes('handover')||(!['completed'].includes(s(r.status))&&String(r.planned_end||'').slice(0,10)>=today&&String(r.planned_end||'').slice(0,10)<=three)),materialPending=M.filter(r=>n(r.received_qty)<n(r.required_qty)),materialDue=M.filter(r=>String(r.expected_delivery||'').slice(0,10)<=three&&n(r.received_qty)<n(r.required_qty)),openService=S.filter(r=>!['closed','resolved','completed'].includes(s(r.status))),urgentService=openService.filter(r=>s(r.priority)==='urgent'||s(r.priority)==='high'),overdueService=openService.filter(r=>String(first(r.scheduled_at,r.updated_at)).slice(0,10)<today),renewals=[...amc.map(r=>({...r,renewal_type:'AMC'})),...warranties.map(r=>({...r,renewal_type:'Warranty',end_date:r.service_end}))].filter(r=>String(r.end_date||'').slice(0,10)>=today&&String(r.end_date||'').slice(0,10)<=day(new Date(Date.now()+30*86400000)));
 const collectionToday=sum([...Pay.filter(r=>within(r.date,today,today)),...IPay.filter(r=>within(r.date,today,today))],"amount"),collectionMonth=sum([...Pay.filter(r=>within(r.date,monthStart,today)),...IPay.filter(r=>within(r.date,monthStart,today))],"amount"),monthExpenses=admin?expenses.filter(r=>within(r.date,monthStart,today)):[],periodExpenses=admin?expenses.filter(r=>within(r.date,dates.from,dates.to)):[],purchasePending=admin?sum(materialPending,"buying_price"):0,expenseTotal=admin?sum(monthExpenses,"amount")+sum(monthExpenses,"tax"):0,purchaseCost=admin?M.reduce((a,r)=>a+n(r.buying_price)*n(r.required_qty)+n(r.freight),0):0;
 const priority=[...followOver.map(r=>({kind:'lead',title:`Overdue follow-up · ${r.customer_name}`,meta:`${r.phone} · ${r.followup_at}`,action:'Call customer',module:'Leads',id:r.id,severity:'high'})),...followToday.map(r=>({kind:'lead',title:`Call today · ${r.customer_name}`,meta:`${r.phone}`,action:'Open lead',module:'Leads',id:r.id})),...siteVisits.map(r=>({kind:'visit',title:String(r.content),meta:String(r.due_at),action:'Complete visit',module:'Leads',id:r.entity_id})),...expiringQ.map(r=>({kind:'quote',title:`${r.number} expires soon`,meta:`${r.customer_name} · ₹${n(r.total).toLocaleString('en-IN')}`,action:'Open quote',module:'Quotations',id:r.id,severity:'high'})),...overdueI.map(r=>({kind:'invoice',title:`Payment overdue · ${r.number}`,meta:`${r.customer_name} · ₹${n(r.grand_total).toLocaleString('en-IN')}`,action:'Record payment',module:'Invoices',id:r.id,severity:'high'})),...installs.map(r=>({kind:'project',title:`Installation today · ${r.title}`,meta:`${r.customer_name} · ${r.site_name}`,action:'Open project',module:'Projects',id:r.id})),...materialDue.map(r=>({kind:'material',title:`Material not received · ${r.name}`,meta:`${r.project_title} · due ${r.expected_delivery}`,action:'Update material',module:'Procurement',id:r.id,severity:'high'})),...urgentService.map(r=>({kind:'service',title:`Urgent service · ${r.customer_name}`,meta:String(r.problem),action:'Assign technician',module:'Service',id:r.id,severity:'high'}))].slice(0,20);
 const stages=['New','Contacted','Site Visit Scheduled','Quote In Progress','Quote Sent','Negotiation','Won','Lost'].map(stage=>{const rows=L.filter(r=>s(r.status)===s(stage));return{stage,count:rows.length,value:rows.reduce((a,r)=>a+n(String(r.budget||'').replace(/[^0-9.]/g,'')),0),module:'Leads',filter:stage}});
 const projectStages=['Confirmed','Advance Received','Procurement','Materials Ready','Materials at Site','Installation Scheduled','Installation','Testing & Configuration','Handover','Completed'].map(stage=>({stage,count:P.filter(r=>s(r.status)===s(stage)).length}));
 const cards=activeP.slice(0,30).map(r=>{const next=T.find(t=>t.project_id===r.id&&!['completed','done'].includes(s(t.status))),mats=M.filter(m=>m.project_id===r.id),received=mats.length&&!mats.some(m=>n(m.received_qty)<n(m.required_qty)),paid=Pay.filter(x=>x.project_id===r.id).reduce((a,x)=>a+n(x.amount),0);return{id:r.id,title:r.title,customer:r.customer_name,site:r.site_name,staff:r.manager_name||'Unassigned',status:r.status,nextTask:next?.title||'No pending task',dueDate:first(next?.due_at,r.planned_end,'Not set'),paymentStatus:paid>=n(r.value)?'Paid':paid>0?`Part paid · ₹${paid.toLocaleString('en-IN')}`:'Advance pending',materialStatus:received?'Materials ready':mats.length?'Materials pending':'Material list pending'}});
 const employeeRows=users.filter(x=>admin||x.id===user.id).map(x=>({id:x.id,name:x.name,role:x.role,leads:L.filter(r=>r.assigned_to===x.id).length,followups:A.filter(r=>r.created_by===x.id&&r.completed_at&&within(r.completed_at,today,today)).length,overdueTasks:T.filter(r=>r.assigned_to===x.id&&!r.completed_at&&String(r.due_at||'9999')<today).length,quotes:Q.filter(r=>r.created_by===x.id&&within(r.created_at,monthStart,today)).length,completed:T.filter(r=>r.assigned_to===x.id&&r.completed_at&&within(r.completed_at,monthStart,today)).length,jobsPending:S.filter(r=>r.assigned_to===x.id&&!['closed','resolved','completed'].includes(s(r.status))).length}));
 const activity=audit.filter(r=>admin||r.user_id===user.id).slice(0,25).map(r=>({id:r.id,time:r.created_at,user:r.user_name||'Team member',text:String(r.action).replaceAll('_',' '),entityType:r.entity_type,entityId:r.entity_id,module:r.entity_type==='tax_invoice'?'Invoices':r.entity_type==='quotation'?'Quotations':r.entity_type==='lead'?'Leads':r.entity_type==='project'?'Projects':r.entity_type==='expense'?'Expenses':'Overview'}));
 const expenseSplit=admin?Object.entries(monthExpenses.reduce((a,r)=>{const k=String(r.category||'Miscellaneous');a[k]=(a[k]||0)+n(r.amount)+n(r.tax);return a},{} as Record<string,number>)).map(([category,value])=>({category,value})).sort((a,b)=>b.value-a.value):[];
 const safeMaterials=materialDue.slice(0,12).map(r=>({id:r.id,name:r.name,sku:r.sku,project_id:r.project_id,project_title:r.project_title,customer_name:r.customer_name,site_name:r.site_name,required_qty:r.required_qty,ordered_qty:r.ordered_qty,received_qty:r.received_qty,status:r.status,expected_delivery:r.expected_delivery}));
 return Response.json({role:user.role,user:{id:user.id,name:user.name},filters:{from:dates.from,to:dates.to,employees:admin?users:[]},kpis:{leads:{new:newLeads.length,notContacted:L.filter(r=>s(r.status)==='new').length,followupsToday:followToday.length,followupsOverdue:followOver.length,siteVisits:siteVisits.length},quotes:{draft:draftQ.length,sent:sentQ.length,value:sum(periodRows(Q,'created_at'),'total'),followup:pendingQ.length,expiring:expiringQ.length,accepted:acceptedQ.length,rejected:rejectedQ.length},invoices:{draft:draftI.length,finalised:finalI.length,value:invoiceTotal,received:paidTotal,pending,overdue:overdueI.length},projects:{active:activeP.length,installationsToday:installs.length,delayed:delayedP.length,handovers:handover.length,waiting:activeP.filter(r=>s(r.status).includes('waiting')||s(r.notes).includes('readiness')).length},procurement:{pending:materialPending.length,due:materialDue.length,...(admin?{purchasePending}:{})},payments:{today:collectionToday,month:collectionMonth,pending,overdue:sum(overdueI,'grand_total')},expenses:admin?{today:sum(expenses.filter(r=>within(r.date,today,today)),'amount'),month:expenseTotal,pending:0,top:expenseSplit[0]?.category||'No expenses'}:null,service:{open:openService.length,assignedToday:S.filter(r=>within(r.updated_at,today,today)).length,overdue:overdueService.length,renewals:renewals.length}},priority,pipeline:stages,quotationPerformance:{created:Q.filter(r=>within(r.created_at,monthStart,today)).length,amount:sum(Q.filter(r=>within(r.created_at,monthStart,today)),'total'),accepted:sum(acceptedQ.filter(r=>within(r.created_at,monthStart,today)),'total'),conversion:Q.length?acceptedQ.length/Q.length*100:0,pending:pendingQ.sort((a,b)=>n(b.total)-n(a.total)).slice(0,8)},collections:{invoiced:invoiceTotal,collected:paidTotal,pending,overdue:sum(overdueI,'grand_total'),invoices:overdueI.slice(0,10),milestones:[{name:'Advance',value:P.filter(r=>s(r.status)==='confirmed').reduce((a,r)=>a+n(r.value)*.2,0)},{name:'Material procurement',value:P.filter(r=>s(r.status).includes('procurement')).reduce((a,r)=>a+n(r.value)*.6,0)},{name:'Installation',value:P.filter(r=>s(r.status).includes('installation')).reduce((a,r)=>a+n(r.value)*.1,0)},{name:'Handover',value:P.filter(r=>s(r.status).includes('handover')).reduce((a,r)=>a+n(r.value)*.1,0)}]},projectStages,projects:cards,procurement:safeMaterials,cash:admin?{sales:sum(finalI.filter(r=>within(r.invoice_date,monthStart,today)),'grand_total'),collections:collectionMonth,expenses:expenseTotal,supplierPending:purchasePending,customerPending:pending,grossMargin:invoiceTotal-purchaseCost,netCash:collectionMonth-expenseTotal-purchasePending,expenseSplit}:null,team:employeeRows,serviceAlerts:{urgent:urgentService.slice(0,8),overdue:overdueService.slice(0,8),renewals:renewals.slice(0,10)},activity});
 }catch(e){return e instanceof Response?e:Response.json({error:e instanceof Error?e.message:"Unable to load overview"},{status:500})}}
